"options":
  "debug":
    "default": !!bool "false"
    "type": "boolean"
    "description": "Enable debug logging"
  "use-syslog":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Setting this to True will allow supporting services to log to syslog.
  "use-internal-endpoints":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Openstack mostly defaults to using public endpoints for
      internal communication between services. If set to True this option
      will configure services to use internal endpoints where possible.
  "openstack-origin":
    "default": "distro"
    "type": "string"
    "description": |
      Repository from which to install OpenStack.

      May be one of the following:

        distro (default)
        ppa:somecustom/ppa (PPA name must include OpenStack Release)
        deb url sources entry|key id
        or a supported Ubuntu Cloud Archive pocket.

      Supported Ubuntu Cloud Archive pockets include:

        cloud:trusty-liberty
        cloud:trusty-juno
        cloud:trusty-kilo
        cloud:trusty-liberty
        cloud:trusty-mitaka

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  "os-admin-network":
    "type": "string"
    "default": !!null ""
    "description": |
      The IP address and netmask of the OpenStack Admin network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for admin endpoints.
  "os-internal-network":
    "type": "string"
    "default": !!null ""
    "description": |
      The IP address and netmask of the OpenStack Internal network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for internal endpoints.
  "os-public-network":
    "type": "string"
    "default": !!null ""
    "description": |
      The IP address and netmask of the OpenStack Public network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for public endpoints.
  "os-public-hostname":
    "type": "string"
    "default": !!null ""
    "description": |
      The hostname or address of the public endpoints created in the keystone
      identity provider.
      .
      This value will be used for public endpoints. For example, an
      os-public-hostname set to 'api-public.example.com' with ssl enabled
      will create the following endpoint for neutron-api:
      .
      https://api-public.example.com:9696/
  "os-internal-hostname":
    "type": "string"
    "default": !!null ""
    "description": |
      The hostname or address of the internal endpoints created in the keystone
      identity provider.
      .
      This value will be used for internal endpoints. For example, an
      os-internal-hostname set to 'api-internal.example.com' with ssl enabled
      will create the following endpoint for neutron-api:
      .
      https://api-internal.example.com:9696/
  "os-admin-hostname":
    "type": "string"
    "default": !!null ""
    "description": |
      The hostname or address of the admin endpoints created in the keystone
      identity provider.
      .
      This value will be used for admin endpoints. For example, an
      os-admin-hostname set to 'api-admin.example.com' with ssl enabled
      will create the following endpoint for neutron-api:
      .
      https://api-admin.example.com:9696/
  "region":
    "default": "RegionOne"
    "type": "string"
    "description": "OpenStack Region"
  "worker-multiplier":
    "type": "float"
    "default": !!null ""
    "description": |
      The CPU core multiplier to use when configuring worker processes.  By
      default, the number of workers for each daemon is set to twice the number
      of CPU cores a service unit has. When deployed in a LXD container, this
      default value will be capped to 4 workers unless this configuration
      option is set.
  "haproxy-server-timeout":
    "type": "int"
    "default": !!int "30000"
    "description": |
      Server timeout configuration in ms for haproxy, used in HA
      configurations.
  "haproxy-client-timeout":
    "type": "int"
    "default": !!int "30000"
    "description": |
      Client timeout configuration in ms for haproxy, used in HA
      configurations.
  "haproxy-queue-timeout":
    "type": "int"
    "default": !!int "5000"
    "description": |
      Queue timeout configuration in ms for haproxy, used in HA
      configurations.
  "haproxy-connect-timeout":
    "type": "int"
    "default": !!int "5000"
    "description": |
      Connect timeout configuration in ms for haproxy, used in HA
      configurations.
  "vip":
    "type": "string"
    "default": !!null ""
    "description": |
      Virtual IP(s) to use to front API services in HA configuration.

      If multiple networks are being used, a VIP should be provided for each
      network, separated by spaces.
  "vip_iface":
    "type": "string"
    "default": "eth0"
    "description": |
      Default network interface to use for HA vip when it cannot be
      automatically determined.
  "vip_cidr":
    "type": "int"
    "default": !!int "24"
    "description": |
      Default CIDR netmask to use for HA vip when it cannot be automatically
      determined.
  "ssl_cert":
    "type": "string"
    "default": !!null ""
    "description": |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Glance's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  "ssl_key":
    "type": "string"
    "default": !!null ""
    "description": |
      SSL key to use with certificate specified as ssl_cert.
  "ssl_ca":
    "type": "string"
    "default": !!null ""
    "description": |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
